version: '3.8'

services:
  aptixbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: aptix/aptixbot:1.2.4
    container_name: aptixbot
    restart: unless-stopped
    ports: 
      - "6185:6185"
      - "6186:6186"
    volumes:
      - ./data:/AptixBot/data
      - ./config:/AptixBot/config
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6185/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
