version: '3.8'

services:
  Aptixbot:
    image: Aptix/Aptixbot:latest
    container_name: Aptixbot
    ports: 
      - "6180-6200:6180-6200"
      - "11451:11451"
    volumes:
      - ./data:/AptixBot/data
